stages:
  - primary

codeFreeze-job:
  image: python:3.15.0a1-alpine3.22
  stage: primary
  tags:
    - docker
  script:
    - |
      apk add curl
      curl --header "Authorization: Bearer glpat-c4SuuACFLPd9A_oCFejJ4G86MQp1OjMH.01.0w0odhjci" http://dockergitlab/api/v4/projects/2/repository/files/config.yml/raw?ref=main -vv  
